brace_style = "PreferSameLine"
fn_args_layout = "Compressed"
ignore = ["src/protocol"]
max_width = 100
tab_spaces = 2
use_small_heuristics = "Max"
where_single_line = true
imports_granularity="Crate"
