[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"
name = "maxwell-protocol"
version = "0.22.0"

[dependencies]
actix = "0.13.3"
bytes = "1.5.0"
prost = "0.12.3"
thiserror = "1.0.58"
