[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"
name = "maxwell-protocol"
version = "0.11.0"

[dependencies]
actix = "0.13.0"
bytes = "1.4.0"
prost = "0.11.9"
thiserror = "1.0.40"
