[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"
name = "maxwell-protocol"
version = "0.18.0"

[dependencies]
actix = "0.13.1"
bytes = "1.5.0"
prost = "0.12.1"
thiserror = "1.0.48"
