[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"
name = "maxwell-protocol"
version = "0.15.1"

[dependencies]
actix = "0.13.1"
bytes = "1.4.0"
prost = "0.12.0"
thiserror = "1.0.47"
