[package]
authors = ["Chaoqian Xu <chaoranxu@gmail.com>"]
edition = "2021"
name = "maxwell-protocol"
version = "0.24.1"

[dependencies]
actix = "0.13.5"
bytes = "1.7.1"
prost = "0.13.2"
thiserror = "1.0.63"
